services: 
  - type: web 
    name: employee-management-system 
    env: python 
    buildCommand: pip install -r requirements.txt 
    startCommand: gunicorn backend.wsgi:application 
    envVars: 
      - key: SECRET_KEY 
        generateValue: true 
      - key: DJANGO_SETTINGS_MODULE 
        value: backend.settings 
